version: '3.1'
services:
  api:
    build: ./api
    container_name: cv-api
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
  web:
    build: ./web
    container_name: cv-web
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true
